config/routes.rb
BinashahartApp::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :abouts

  resources :paintings

  resources :admins

  resources :homes

  resources :abouts 
  resources :homepage
  resources :abstracts
  resources :torsos
  resources :blues
  resources :vessels
  resources :figures
  resources :blooms

  root :to => "homes#index"

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :description, :subtitle, :image

  mount_uploader :image, ImageUploader
end

app/models/abstract.rb
class Abstract < ActiveRecord::Base
  attr_accessible :description, :title
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/bloom.rb
class Bloom < ActiveRecord::Base
  attr_accessible :description, :title, :image

  mount_uploader :image, ImageUploader
end

app/models/blue.rb
class Blue < ActiveRecord::Base
  attr_accessible :description, :title, :image

  mount_uploader :image, ImageUploader
end

app/models/figure.rb
class Figure < ActiveRecord::Base
  attr_accessible :description, :title, :image

  mount_uploader :image, ImageUploader
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :description, :title, :image

  mount_uploader :image, ImageUploader
end

app/models/torso.rb
class Torso < ActiveRecord::Base
  attr_accessible :description, :title, :image

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_uniqueness_of :email

end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
  attr_accessible :description, :title, :image

  mount_uploader :image, ImageUploader
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/blooms_helper.rb
module BloomsHelper
end

app/helpers/blues_helper.rb
module BluesHelper
end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/torsos_helper.rb
module TorsosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Admin Panel</h1>

<h4>Add More Photos</h4>
<p>New Bloom:  <%= link_to "Add a New Bloom Photo", new_bloom_path %></p>
<p>New Figure:  <%= link_to "Add a New Figure Photo", new_figure_path %></p>
<p>New Vessel:  <%= link_to "Add a New Vessel Photo", new_vessel_path %></p>
<p>New Blue:  <%= link_to "Add a New Blue Photo", new_blue_path %></p>
<p>New Torso:  <%= link_to "Add a New Torso Photo", new_torso_path %></p>
<p>New Abstract:  <%= link_to 'Add a New Painting Photo', new_painting_path %></p>


<h2>About Section</h2>

<%= link_to 'View', abouts_path %>,
<%= link_to 'New', new_about_path %>,  


<% @abouts.each do |about| %>
  <%= link_to 'View About Page', about %>, 
  <%= link_to 'Edit About Page', edit_about_path(about) %>
    <%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


<hr>
<h2>Blooms</h2>

<% @blooms.each do |bloom| %>
    <div class="row">
        <%= bloom.title %>
        <%= link_to 'Show', bloom %>, 
        <%= link_to 'Edit', edit_bloom_path(bloom) %>, 
        <%= link_to 'Destroy', bloom, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>

<hr>
<h2>Blues</h2>
<% @blues.each do |blue| %>
    <div class="row">
        <%= blue.title %>
        <%= link_to 'Show', blue %>, 
        <%= link_to 'Edit', edit_blue_path(blue) %>, 
        <%= link_to 'Destroy', blue, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
<hr>
<h2>Figures</h2>
<% @figures.each do |figure| %>
    <div class="row">
        <%= figure.title %>
        <%= link_to 'Show', figure %>, 
        <%= link_to 'Edit', edit_figure_path(figure) %>, 
        <%= link_to 'Destroy', figure, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
<hr>
<h2>Torsos</h2>
<% @torsos.each do |torso| %>
    <div class="row">
        <%= torso.title %>
        <%= link_to 'Show', torso %>, 
        <%= link_to 'Edit', edit_torso_path(torso) %>, 
        <%= link_to 'Destroy', torso, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
<hr>
<h2>Vessels</h2>
<% @vessels.each do |vessel| %>
    <div class="row">
        <%= vessel.title %>
        <%= link_to 'Show', vessel %>,
        <%= link_to 'Edit', edit_vessel_path(vessel) %>,
        <%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
<hr>
<h2>Abstracts</h2>
<% @paintings.each do |painting| %>
    <div class="row">
        <%= painting.title %>
        <%= painting.description %>
        <%= link_to 'Show', painting %>
        <%= link_to 'Edit', edit_painting_path(painting) %>
        <%= link_to 'Destroy', painting, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bina's Art</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container" id="header">
    <div class="sixteen columns">
      <h1 id="header">Bina Shah</h1>
    </div>
  </div>
<%= yield %>
<footer>
  <div class="container">
    <div class="sixteen columns" id="footie">
      <br>
        <%= link_to "Home", homes_path %>
        |
        <%= link_to "About", abouts_path %>
        |
        <%= link_to "Blooms", blooms_path %>
        |
        <%= link_to "Blues", blues_path %>
        |
        <%= link_to "Figures", figures_path %>
        |
        <%= link_to "Abstracts", paintings_path %>
        |
        <%= link_to "Torsos", torsos_path %>
        |
        <%= link_to "Vessels", vessels_path %>
      <br>
      <br>
      <p>&copy;Bina Shah</p>
      <p>Created by <a href="http://www.nehashah.info" target="_blank">Néha Shah</a>
    </div>
  </div>
</footer>
</body>
</html>